namespace WallyMapSpinzor2;

//This enum is merely for convenience.
//Do not use it as a type of paramater, since that could break with newer scoring types.
public enum ScoringTypeEnum
{
    //use 0 for none
    XLTemplate = 1,
    TIMED,
    STOCK,
    BRAWLBALL,
    BOMBSKETBALL,
    RICOCHET,
    HOLDTHETHING,
    CONQUEST,
    DODGEBALL,
    VOLLEYBALL,
    GAUNTLET,
    HOTPOTATO,
    ARCADE,
    HYDRA,
    SNOWBALL,
    RELAY,
    CATCHBOMBS,
    HOCKEY,
    TAUNTBRAWL,
    SIMON,
    BOUNTYHUNTER,
    SCRAMBLE,
    COLORPLATFORMS,
    POGO,
    SKEEBOMB,
    SUPERBRAWL,
    GIANT,
    PARTYMODE,
    KOTH,
    CTF,
    RICOCHETTIMED,
    TIMEDWATERBOMB,
    HAUNTEDFLOORS,
    SOCCER,
    HORDE,
    BUDDY,
    RING,
    TAG,
    SHIFT,
    CLIMB,
    SHOWDOWN,
    ZOMBIE,
    CREWBATTLE,
    SHIFTTIMED,
    STREET_BRAWL,
    BOUNTY_V2,
    TABLETOP,
    VOLLEY_BATTLE,
    OOPS_ALL_BOOMERANGS,
    ODDBRAWL,
    BOMBMANIA,
    STREET_BRAWL_RELAY
}